sudo: false

language: python

python:
  - "3.5"
  - "3.6"

install: pip install tox-travis coveralls

script: tox

after_success: coveralls

notifications:
  irc:
    channels:
      - "chat.freenode.net#asphalt"
    on_success: change
    on_failure: change
    use_notice: true
    skip_join: true

deploy:
  provider: pypi
  user: agronholm
  password:
    secure: GKXgo5gQVNo5FQx/jvYjw0wQp/1hhZRAfozr+zWucRxdfbVBFGtdhAQZSAt9bVa9UcgriVtGd8vIFQMvPEh/8fKWJ8atTxdR8iLbI8ujl6lRqUB4y0q4Umkv90BuXcVMQPzddpwYTN26CK3Ajb8Q58fiRruDa3g+QL3JZOh/h0fMKwZ84pd/Gz5xfcHAsb1iykoWC+iECN5VWW7bZ+UN5zGToULrZ3N3pwhOope7cWLH99FGgc9JfcU+Ttk+wVOUdxmWGHY4JOuwRppsEgdA3pPhVRgFbFFxJlXNEtcUPNtHuJ3OQC/xdYfF/sVJ68UfX4Lqm83LImxrxkXKmCGoNA+c98Zi4KozvlFbGeFdJXHPECjhOu1IusZc80cIwtdBiqblJFw097R13AF1WZiDVBLWBEGdu17YFlmaHLCDn1YlQsEXJmrfj0+tabP0yb1Ibon8TP0MGMdOyJLeZrYYMLl4eP6TJDY46c8r67NUShhuDyn9VduVJwNaOt3GLihp+CO5fxLnn01rdwOQ1B5ORmXfWR5CyEehdm0qWOfhdAPtu8pro4Zl5WRg+RIQNi2VyF5o7oHN/ta0hwpnQ/d0uJx6140aH1EIx4OSzZaOeA223IJZWeySgBz1MEIMwQFSZPrXaTsKgDI0My4eaBGKkhEK2uFJcLt4vnKWWMRg760=
  distributions: sdist bdist_wheel
  on:
    tags: true
    python: "3.5"
    repo: asphalt-framework/asphalt-templating
